namespace doDonor
{
    partial class FormCariJadwal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.btnSearch = new Guna.UI2.WinForms.Guna2GradientButton();
            this.cbRegion = new System.Windows.Forms.ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.guna2HtmlLabel1 = new Guna.UI2.WinForms.Guna2HtmlLabel();
            this.SuspendLayout();
            // 
            // btnSearch
            // 
            this.btnSearch.BorderRadius = 15;
            this.btnSearch.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnSearch.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnSearch.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnSearch.DisabledState.FillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnSearch.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnSearch.FillColor2 = System.Drawing.Color.IndianRed;
            this.btnSearch.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnSearch.ForeColor = System.Drawing.Color.White;
            this.btnSearch.Location = new System.Drawing.Point(139, 288);
            this.btnSearch.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Size = new System.Drawing.Size(381, 41);
            this.btnSearch.TabIndex = 31;
            this.btnSearch.Text = "Cari";
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            // 
            // cbRegion
            // 
            this.cbRegion.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbRegion.FormattingEnabled = true;
            this.cbRegion.Items.AddRange(new object[] {
            "Semua",
            "Aceh Barat",
            "Aceh Barat Daya",
            "Aceh Besar",
            "Aceh Jaya",
            "Aceh Selatan",
            "Aceh Singkil",
            "Aceh Tamiang",
            "Aceh Tengah",
            "Aceh Tenggara",
            "Aceh Timur",
            "Aceh Utara",
            "Agam",
            "Alor",
            "Ambon",
            "Asahan",
            "Asmat",
            "Batam",
            "Badung",
            "Balangan",
            "Balikpapan",
            "Banda Aceh",
            "Bandar Lampung",
            "Bandung",
            "Bandung Barat",
            "Banggai",
            "Banggai Kepulauan",
            "Banggai Laut",
            "Bangka",
            "Bangka Barat",
            "Bangka Selatan",
            "Bangka Tengah",
            "Bangkalan",
            "Bangli",
            "Banjar",
            "Banjar Baru",
            "Banjarmasin",
            "Banjarnegara",
            "Bantaeng",
            "Bantul",
            "Banyu Asin",
            "Banyumas",
            "Banyuwangi",
            "Barito Kuala",
            "Barito Selatan",
            "Barito Timur",
            "Barito Utara",
            "Barru",
            "Baru",
            "Batang",
            "Batang Hari",
            "Batu",
            "Batu Bara",
            "Baubau",
            "Bekasi",
            "Belitung",
            "Belitung Timur",
            "Belu",
            "Bener Meriah",
            "Bengkalis",
            "Bengkayang",
            "Bengkulu",
            "Bengkulu Selatan",
            "Bengkulu Tengah",
            "Bengkulu Utara",
            "Berau",
            "Biak Numfor",
            "Bima",
            "Binjai",
            "Bintan",
            "Bireuen",
            "Bitung",
            "Blitar",
            "Blora",
            "Boalemo",
            "Bogor",
            "Bojonegoro",
            "Bolaang Mongondow",
            "Bolaang Mongondow Selatan",
            "Bolaang Mongondow Timur",
            "Bolaang Mongondow Utara",
            "Bombana",
            "Bondowoso",
            "Bone",
            "Bone Bolango",
            "Bontang",
            "Boven Digoel",
            "Boyolali",
            "Brebes",
            "Bukittinggi",
            "Buleleng",
            "Bulukumba",
            "Bulungan",
            "Bungo",
            "Buol",
            "Buru",
            "Buru Selatan",
            "Buton",
            "Buton Selatan",
            "Buton Tengah",
            "Buton Utara",
            "Ciamis",
            "Cianjur",
            "Cilacap",
            "Cilegon",
            "Cimahi",
            "Cirebon",
            "Dumai",
            "Dairi",
            "Deiyai",
            "Deli Serdang",
            "Demak",
            "Denpasar",
            "Depok",
            "Dharmasraya",
            "Dogiyai",
            "Dompu",
            "Donggala",
            "Empat Lawang",
            "Ende",
            "Enrekang",
            "Fakfak",
            "Flores Timur",
            "Garut",
            "Gayo Lues",
            "Gianyar",
            "Gorontalo",
            "Gorontalo Utara",
            "Gowa",
            "Gresik",
            "Grobogan",
            "Gunung Kidul",
            "Gunung Mas",
            "Gunungsitoli",
            "Halmahera Barat",
            "Halmahera Selatan",
            "Halmahera Tengah",
            "Halmahera Timur",
            "Halmahera Utara",
            "Hulu Sungai Selatan",
            "Hulu Sungai Tengah",
            "Hulu Sungai Utara",
            "Humbang Hasundutan",
            "Indragiri Hilir",
            "Indragiri Hulu",
            "Indramayu",
            "Intan Jaya",
            "Jakarta Barat",
            "Jakarta Pusat",
            "Jakarta Selatan",
            "Jakarta Timur",
            "Jakarta Utara",
            "Jambi",
            "Jayapura",
            "Jayawijaya",
            "Jember",
            "Jembrana",
            "Jeneponto",
            "Jepara",
            "Jombang",
            "Kaimana",
            "Kampar",
            "Kapuas",
            "Kapuas Hulu",
            "Karang Asem",
            "Karanganyar",
            "Karawang",
            "Karimun",
            "Karo",
            "Katingan",
            "Kaur",
            "Kayong Utara",
            "Kebumen",
            "Kediri",
            "Keerom",
            "Kendal",
            "Kendari",
            "Kepahiang",
            "Kepulauan Anambas",
            "Kepulauan Aru",
            "Kepulauan Mentawai",
            "Kepulauan Meranti",
            "Kepulauan Sangihe",
            "Kepulauan Selayar",
            "Kepulauan Seribu",
            "Kepulauan Sula",
            "Kepulauan Talaud",
            "Kepulauan Yapen",
            "Kerinci",
            "Ketapang",
            "Klaten",
            "Klungkung",
            "Kolaka",
            "Kolaka Timur",
            "Kolaka Utara",
            "Konawe",
            "Konawe Kepulauan",
            "Konawe Selatan",
            "Konawe Utara",
            "Kotamobagu",
            "Kotawaringin Barat",
            "Kotawaringin Timur",
            "Kuantan Singingi",
            "Kubu Raya",
            "Kudus",
            "Kulon Progo",
            "Kuningan",
            "Kupang",
            "Kutai Barat",
            "Kutai Kartanegara",
            "Kutai Timur",
            "Labuhan Batu",
            "Labuhan Batu Selatan",
            "Labuhan Batu Utara",
            "Lahat",
            "Lamandau",
            "Lamongan",
            "Lampung Barat",
            "Lampung Selatan",
            "Lampung Tengah",
            "Lampung Timur",
            "Lampung Utara",
            "Landak",
            "Langkat",
            "Langsa",
            "Lanny Jaya",
            "Lebak",
            "Lebong",
            "Lembata",
            "Lhokseumawe",
            "Lima Puluh Kota",
            "Lingga",
            "Lombok Barat",
            "Lombok Tengah",
            "Lombok Timur",
            "Lombok Utara",
            "Lubuklinggau",
            "Lumajang",
            "Luwu",
            "Luwu Timur",
            "Luwu Utara",
            "Madiun",
            "Magelang",
            "Magetan",
            "Mahakam Hulu",
            "Majalengka",
            "Majene",
            "Makassar",
            "Malaka",
            "Malang",
            "Malinau",
            "Maluku Barat Daya",
            "Maluku Tengah",
            "Maluku Tenggara",
            "Maluku Tenggara Barat",
            "Mamasa",
            "Mamberamo Raya",
            "Mamberamo Tengah",
            "Mamuju",
            "Mamuju Tengah",
            "Mamuju Utara",
            "Manado",
            "Mandailing Natal",
            "Manggarai",
            "Manggarai Barat",
            "Manggarai Timur",
            "Manokwari",
            "Manokwari Selatan",
            "Mappi",
            "Maros",
            "Mataram",
            "Maybrat",
            "Medan",
            "Melawi",
            "Mempawah",
            "Merangin",
            "Merauke",
            "Mesuji",
            "Metro",
            "Mimika",
            "Minahasa",
            "Minahasa Selatan",
            "Minahasa Tenggara",
            "Minahasa Utara",
            "Mojokerto",
            "Morowali",
            "Morowali Utara",
            "Muara Enim",
            "Muaro Jambi",
            "Mukomuko",
            "Muna",
            "Muna Barat",
            "Murung Raya",
            "Musi Banyuasin",
            "Musi Rawas",
            "Musi Rawas Utara",
            "Nabire",
            "Nagan Raya",
            "Nagekeo",
            "Natuna",
            "Nduga",
            "Ngada",
            "Nganjuk",
            "Ngawi",
            "Nias",
            "Nias Barat",
            "Nias Selatan",
            "Nias Utara",
            "Nunukan",
            "Ogan Ilir",
            "Ogan Komering Ilir",
            "Ogan Komering Ulu",
            "Ogan Komering Ulu Selatan",
            "Ogan Komering Ulu Timur",
            "Pacitan",
            "Padang",
            "Padang Lawas",
            "Padang Lawas Utara",
            "Padang Panjang",
            "Padang Pariaman",
            "Padangsidimpuan",
            "Pagar Alam",
            "Pakpak Bharat",
            "Palangka Raya",
            "Palembang",
            "Palopo",
            "Palu",
            "Pamekasan",
            "Pandeglang",
            "Pangandaran",
            "Pangkajene Dan Kepulauan",
            "Pangkal Pinang",
            "Paniai",
            "Parepare",
            "Pariaman",
            "Parigi Moutong",
            "Pasaman",
            "Pasaman Barat",
            "Paser",
            "Pasuruan",
            "Pati",
            "Payakumbuh",
            "Pegunungan Arfak",
            "Pegunungan Bintang",
            "Pekalongan",
            "Pekanbaru",
            "Pelalawan",
            "Pemalang",
            "Pematang Siantar",
            "Penajam Paser Utara",
            "Penukal Abab Lematang Ilir",
            "Pesawaran",
            "Pesisir Barat",
            "Pesisir Selatan",
            "Pidie",
            "Pidie Jaya",
            "Pinrang",
            "Pohuwato",
            "Polewali Mandar",
            "Ponorogo",
            "Pontianak",
            "Poso",
            "Prabumulih",
            "Pringsewu",
            "Probolinggo",
            "Pulang Pisau",
            "Pulau Morotai",
            "Pulau Taliabu",
            "Puncak",
            "Puncak Jaya",
            "Purbalingga",
            "Purwakarta",
            "Purworejo",
            "Raja Ampat",
            "Rejang Lebong",
            "Rembang",
            "Rokan Hilir",
            "Rokan Hulu",
            "Rote Ndao",
            "Siak",
            "Sabang",
            "Sabu Raijua",
            "Salatiga",
            "Samarinda",
            "Sambas",
            "Samosir",
            "Sampang",
            "Sanggau",
            "Sarmi",
            "Sarolangun",
            "Sawah Lunto",
            "Sekadau",
            "Seluma",
            "Semarang",
            "Seram Bagian Barat",
            "Seram Bagian Timur",
            "Serang",
            "Serdang Bedagai",
            "Seruyan",
            "Siau Tagulandang Biaro",
            "Sibolga",
            "Sidenreng Rappang",
            "Sidoarjo",
            "Sigi",
            "Sijunjung",
            "Sikka",
            "Simalungun",
            "Simeulue",
            "Singkawang",
            "Sinjai",
            "Sintang",
            "Situbondo",
            "Sleman",
            "Solok",
            "Solok Selatan",
            "Soppeng",
            "Sorong",
            "Sorong Selatan",
            "Sragen",
            "Subang",
            "Subulussalam",
            "Sukabumi",
            "Sukamara",
            "Sukoharjo",
            "Sumba Barat",
            "Sumba Barat Daya",
            "Sumba Tengah",
            "Sumba Timur",
            "Sumbawa",
            "Sumbawa Barat",
            "Sumedang",
            "Sumenep",
            "Sungai Penuh",
            "Supiori",
            "Surabaya",
            "Surakarta",
            "Tabalong",
            "Tabanan",
            "Takalar",
            "Tambrauw",
            "Tana Tidung",
            "Tana Toraja",
            "Tanah Bumbu",
            "Tanah Datar",
            "Tanah Laut",
            "Tangerang",
            "Tangerang Selatan",
            "Tanggamus",
            "Tanjung Balai",
            "Tanjung Jabung Barat",
            "Tanjung Jabung Timur",
            "Tanjung Pinang",
            "Tapanuli Selatan",
            "Tapanuli Tengah",
            "Tapanuli Utara",
            "Tapin",
            "Tarakan",
            "Tasikmalaya",
            "Tebing Tinggi",
            "Tebo",
            "Tegal",
            "Teluk Bintuni",
            "Teluk Wondama",
            "Temanggung",
            "Ternate",
            "Tidore Kepulauan",
            "Timor Tengah Selatan",
            "Timor Tengah Utara",
            "Toba Samosir",
            "Tojo Una-Una",
            "Tolikara",
            "Toli-Toli",
            "Tomohon",
            "Toraja Utara",
            "Trenggalek",
            "Tual",
            "Tuban",
            "Tulang Bawang Barat",
            "Tulangbawang",
            "Tulungagung",
            "Wajo",
            "Wakatobi",
            "Waropen",
            "Way Kanan",
            "Wonogiri",
            "Wonosobo",
            "Yahukimo",
            "Yalimo",
            "Yogyakarta"});
            this.cbRegion.Location = new System.Drawing.Point(139, 230);
            this.cbRegion.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.cbRegion.Name = "cbRegion";
            this.cbRegion.Size = new System.Drawing.Size(381, 28);
            this.cbRegion.TabIndex = 30;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label1.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label1.Location = new System.Drawing.Point(195, 92);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(275, 41);
            this.label1.TabIndex = 29;
            this.label1.Text = "Cari Jadwal Donor";
            // 
            // guna2HtmlLabel1
            // 
            this.guna2HtmlLabel1.BackColor = System.Drawing.Color.Transparent;
            this.guna2HtmlLabel1.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.guna2HtmlLabel1.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.guna2HtmlLabel1.Location = new System.Drawing.Point(139, 198);
            this.guna2HtmlLabel1.Name = "guna2HtmlLabel1";
            this.guna2HtmlLabel1.Size = new System.Drawing.Size(135, 25);
            this.guna2HtmlLabel1.TabIndex = 32;
            this.guna2HtmlLabel1.Text = "Kota/Kabupaten";
            // 
            // FormCariJadwal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(30)))), ((int)(((byte)(45)))));
            this.ClientSize = new System.Drawing.Size(676, 548);
            this.Controls.Add(this.guna2HtmlLabel1);
            this.Controls.Add(this.btnSearch);
            this.Controls.Add(this.cbRegion);
            this.Controls.Add(this.label1);
            this.Name = "FormCariJadwal";
            this.Text = "FormCariJadwal";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2GradientButton btnSearch;
        private ComboBox cbRegion;
        private Label label1;
        private Guna.UI2.WinForms.Guna2HtmlLabel guna2HtmlLabel1;
    }
}